language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - composer install --no-dev
  - sudo wget http://alexeyrybak.com/blitz/all-releases/blitz-0.8.17.tar.gz
  - sudo tar zxvf blitz-0.8.17.tar.gz
  - sudo cd blitz-0.8.17
  - sudo phpize
  - sudo ./configure
  - sudo make install

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover